name: diagrame echo testing

on: [push]

env:
  NODE_ENV: developement
  TAG_1: true

jobs:
  health-check:
    runs-on: ubuntu-latest
    env:
      TOKEN: "some token"
    steps:
      - name: basic health check
        run: | 
          echo NODE ENV === ${{env.NODE_ENV}}

  flavor_1:
    runs-on: ubuntu-latest
    needs: [health-check]
    env:
      Greeting: Hello
    steps:
      - name: "developement flavor"
        run: | 
          echo -e "\034[31;1;4mquick testd\034[0m"
          echo "proof of concept for NODE_ENV=== ${{env.NODE_ENV}}"

  flavor_2:
    runs-on: ubuntu-latest
    needs: [health-check]
    steps:
      - name: "production-new company flavor"
        env:
          NODE_ENV: production-new-company 
        run: |
          echo -e "\033[31;1;4madvanced\033[0m"
          echo "create new company for NODE_ENV=== ${{env.NODE_ENV}}"
  
  flavor_conditional:
    runs-on: ubuntu-latest
    needs: [health-check, flavor_2]
    env:
      Greeting: Hello
    steps:
      - name: conditional runing with tags
        if: ${{ env.TAG_1 == 'true' }}
        run: echo "$Greeting $API_KEY. Today is $TAG_1 !"
        env:
          API_KEY: some-key
            
