name: diagrame echo testing

on: 
  push:
    branches:
      - production
  pull_request:

env:
  NODE_ENV: production
  TAG_1: true

jobs:
  health-check:
    runs-on: ubuntu-latest
    env:
      TOKEN: "some token"
    steps:
      - name: basic health check
        run: | 
          echo NODE ENV === ${{env.NODE_ENV}}

  flavor:
    runs-on: ubuntu-latest
    needs: [health-check]
    env:
      Greeting: Hello
    steps:
      - name: "developement flavor"
        run: | 
          echo -e "\034[31;1;4mquick-testd\034[0m"
          echo "proof of concept for NODE_ENV=== ${{env.NODE_ENV}}"

  flavor_conditional:
    runs-on: ubuntu-latest
    needs: [health-check, flavor]
    env:
      Greeting: Hello
    steps:
      - name: conditional runing with tags
        if: ${{ env.TAG_1 == 'true' }}
        run: echo "$Greeting $API_KEY. Today is $TAG_1 !"
        env:
          API_KEY: some-key
            
